=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/schema/component-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_set_component",
    "version": "0.1",
    "url": "TODO",
    "description": "Basis Set Exchange - A component of a basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "description",
        "data_source",
        "elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "component" ]
                },
                "schema_version": {
                    "description": "Version of the BSE basis set component schema being used",
                    "type": "string"
                }
            }
        },
        "description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "data_source": {
            "description": "Where the actual numbers in this file came from",
            "type": "string"
        },
        "notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "description": "Data for a single element or atom in the basis set",
                    "type": "object",
                    "required": [
                        "references"
                    ],
                    "additionalProperties": false,
                    "properties": {
                        "references": {
                            "$ref": "common-definitions.json#reference_keys"
                        },
                        "electron_shells": {
                            "$ref": "common-definitions.json#electron_shell_list"
                        },
                        "ecp_electrons":
                        {
                            "$ref": "common-definitions.json#ecp_electrons"
                        },
                        "ecp_potentials": {
                            "$ref": "common-definitions.json#ecp_potential_list"
                        }
                    }
                }
            }
        }
    }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/psx/psx-dz.1.json
{
  "molssi_bse_schema": {
    "schema_type": "component",
    "schema_version": "0.1"
  },
  "description": "Even-tempered PsX-DZ positronic basis",
  "data_source": "Data from supporting information",
  "elements": {
    "1": {
      "references": [
        "moncada2020a"
      ],
      "electron_shells": [
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            0
          ],
          "exponents": [
            "1.900000000e-02"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            0
          ],
          "exponents": [
            "5.194600000e-02"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            0
          ],
          "exponents": [
            "1.420203640e-01"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            0
          ],
          "exponents": [
            "3.882836752e-01"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            0
          ],
          "exponents": [
            "1.061567568e+00"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            1
          ],
          "exponents": [
            "5.910000000e-02"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            1
          ],
          "exponents": [
            "1.612839000e-01"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto",
          "region": "",
          "angular_momentum": [
            1
          ],
          "exponents": [
            "4.401437631e-01"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto_spherical",
          "region": "",
          "angular_momentum": [
            2
          ],
          "exponents": [
            "1.165000000e-01"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        },
        {
          "function_type": "gto_spherical",
          "region": "",
          "angular_momentum": [
            2
          ],
          "exponents": [
            "3.128025000e-01"
          ],
          "coefficients": [
            [
              "1.0"
            ]
          ]
        }
      ]
    }
  }
}
