=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/schema/element-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_element_basis_set",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing how a element-based basis set is composed",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "name",
        "description",
        "elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "element" ]
                },
                "schema_version": {
                    "description": "Version of the BSE element basis set schema being used",
                    "type": "string"
                }
            }
        },
        "name": {
            "description": "Common name for the basis set",
            "type": "string"
        },
        "description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "description": "Data for a single element in the basis set",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [ "components" ],
                    "properties": {
                        "components": {
                            "description": "Component files for this element",
                            "type": "array",
                            "minItems": 1,
                            "uniqueItems": true,
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/tests/fakedata/fake/bppfakebasis-jkfit.1.element.json
{
  "molssi_bse_schema": {
    "schema_type": "element",
    "schema_version": "0.1"
  },
  "name": "bppfakebasis-jkfit",
  "description": "A fake jkfit basis set for testing the BSE",
  "elements": {
    "1": {
      "components": [
        "fake/bppfakebasis_fakeref2019a.1.json"
      ]
    }
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/ranasinghe/6zap.1.element.json
{
  "molssi_bse_schema": {
    "schema_type": "element",
    "schema_version": "0.1"
  },
  "name": "6ZaP",
  "description": "6ZaP basis set of Zhong, Barnes, and Petersson",
  "elements": {
    "1": {
      "components": [
        "ranasinghe/6zap.1.json"
      ]
    },
    "6": {
      "components": [
        "ranasinghe/6zap.1.json"
      ]
    },
    "7": {
      "components": [
        "ranasinghe/6zap.1.json"
      ]
    },
    "8": {
      "components": [
        "ranasinghe/6zap.1.json"
      ]
    },
    "9": {
      "components": [
        "ranasinghe/6zap.1.json"
      ]
    }
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/jorge/DZP-ZORA.1.element.json
{
  "molssi_bse_schema": {
    "schema_type": "element",
    "schema_version": "0.1"
  },
  "name": "jorge-DZP-ZORA",
  "description": "DZP-ZORA: All-electron double zeta valence quality plus polarization functions (ZORA)",
  "elements": {
    "1": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "2": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "3": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "4": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "5": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "6": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "7": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "8": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "9": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "10": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "11": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "12": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "13": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "14": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "15": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "16": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "17": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "18": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "19": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "20": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "21": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "22": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "23": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "24": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "25": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "26": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "27": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "28": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "29": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "30": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "31": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "32": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "33": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "34": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "35": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "36": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "37": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "38": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "39": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "40": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "41": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "42": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "43": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "44": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "45": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "46": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "47": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "48": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "49": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "50": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "51": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "52": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "53": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "54": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "55": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "56": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "57": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "72": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "73": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "74": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "75": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "76": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "77": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "78": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "79": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "80": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "81": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "82": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "83": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "84": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "85": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "86": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "87": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "88": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    },
    "89": {
      "components": [
        "jorge/DZP-ZORA.1.json"
      ]
    }
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/dyall/dyall-aae2z.1.element.json
{
  "molssi_bse_schema": {
    "schema_type": "element",
    "schema_version": "0.1"
  },
  "name": "dyall-aae2z",
  "description": "Dyall's augmented all-electron 2-zeta primitive basis set",
  "elements": {
    "1": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "2": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "3": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "4": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "5": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "6": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "7": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "8": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "9": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "10": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "11": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "12": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "13": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "14": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "15": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "16": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "17": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "18": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "19": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "20": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "21": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "22": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "23": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "24": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "25": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "26": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "27": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "28": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "29": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "30": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "31": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "32": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "33": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "34": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "35": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "36": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "37": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "38": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "39": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "40": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "41": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "42": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "43": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "44": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "45": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "46": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "47": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "48": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "49": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "50": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "51": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "52": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "53": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "54": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "55": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "56": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "72": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "73": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "74": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "75": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "76": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "77": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "78": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "79": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "80": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "81": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "82": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "83": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "84": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "85": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "86": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "87": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "88": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "104": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "105": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "106": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "107": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "108": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "109": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "110": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "111": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "112": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "113": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "114": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "115": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "116": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "117": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    },
    "118": {
      "components": [
        "dyall/dyall-aae2z.1.json"
      ]
    }
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/grimme/vdzp.1.element.json
{
  "molssi_bse_schema": {
    "schema_type": "element",
    "schema_version": "0.1"
  },
  "name": "Grimme vDZP",
  "description": "Small basis set used in wB97X-3c method",
  "elements": {
    "1": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "2": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "3": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "4": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "5": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "6": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "7": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "8": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "9": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "10": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "11": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "12": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "13": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "14": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "15": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "16": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "17": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "18": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "19": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "20": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "21": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "22": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "23": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "24": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "25": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "26": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "27": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "28": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "29": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "30": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "31": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "32": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "33": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "34": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "35": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "36": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "37": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "38": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "39": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "40": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "41": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "42": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "43": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "44": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "45": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "46": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "47": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "48": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "49": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "50": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "51": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "52": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "53": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "54": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "55": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "56": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "57": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "58": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "59": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "60": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "61": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "62": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "63": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "64": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "65": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "66": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "67": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "68": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "69": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "70": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "71": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "72": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "73": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "74": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "75": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "76": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "77": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "78": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "79": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "80": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "81": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "82": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "83": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "84": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "85": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    },
    "86": {
      "components": [
        "grimme/vdzp.1.json"
      ]
    }
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/paw/paw-l2.1.element.json
{
  "molssi_bse_schema": {
    "schema_type": "element",
    "schema_version": "0.1"
  },
  "name": "PAW-L2",
  "description": "PAW-L2 basis set for use with PAW method",
  "elements": {
    "1": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "3": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "4": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "5": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "6": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "7": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "8": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "9": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "11": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "12": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "13": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "14": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "15": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "16": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    },
    "17": {
      "components": [
        "paw/paw-l2.1.json"
      ]
    }
  }
}
