=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/schema/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_metadata",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing metadata for a single basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "names",
        "tags",
        "family",
        "description",
        "role",
        "auxiliaries"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "metadata" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "names": {
            "description": "Common names/capitalization of the basis set",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": { "type": "string" }
        },
        "family": {
            "description": "Broad family that the basis set is from",
            "type": "string"
        },
        "description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "tags": {
            "$ref": "common-definitions.json#tags"
        },
        "role": {
            "$ref": "common-definitions.json#role"
        },
        "auxiliaries": {
            "$ref": "common-definitions.json#auxiliaries"
        }
    }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/jorge-TZP-ZORA.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "jorge-TZP-ZORA",
    "TZP-ZORA"
  ],
  "tags": [],
  "family": "jorge",
  "description": "TZP-ZORA, all-electron triple-zeta basis for calculations with the ZORA approach",
  "role": "orbital",
  "auxiliaries": {}
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/jorge-DZP-ZORA.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "jorge-DZP-ZORA"
  ],
  "tags": [],
  "family": "jorge",
  "description": "DZP-ZORA: All-electron double zeta valence quality plus polarization functions (ZORA)",
  "role": "orbital",
  "auxiliaries": {}
}
