=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/schema/table-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_table_basis_set",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing how a table-based basis set is composed",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "revision_date",
        "revision_description",
        "elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "table" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "revision_date": {
            "$ref": "common-definitions.json#revision_date"
        },
        "revision_description": {
            "$ref": "common-definitions.json#revision_description"
        },
        "elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "description": "Elemental basis data to use for this element",
                    "type": "string"
                }
            }
        }
    }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/dyall-ae2z.1.table.json
{
  "molssi_bse_schema": {
    "schema_type": "table",
    "schema_version": "0.1"
  },
  "revision_description": "Data from https://zenodo.org/records/7574629",
  "revision_date": "2024-11-17",
  "elements": {
    "1": "dyall/dyall-ae2z.1.element.json",
    "2": "dyall/dyall-ae2z.1.element.json",
    "3": "dyall/dyall-ae2z.1.element.json",
    "4": "dyall/dyall-ae2z.1.element.json",
    "5": "dyall/dyall-ae2z.1.element.json",
    "6": "dyall/dyall-ae2z.1.element.json",
    "7": "dyall/dyall-ae2z.1.element.json",
    "8": "dyall/dyall-ae2z.1.element.json",
    "9": "dyall/dyall-ae2z.1.element.json",
    "10": "dyall/dyall-ae2z.1.element.json",
    "11": "dyall/dyall-ae2z.1.element.json",
    "12": "dyall/dyall-ae2z.1.element.json",
    "13": "dyall/dyall-ae2z.1.element.json",
    "14": "dyall/dyall-ae2z.1.element.json",
    "15": "dyall/dyall-ae2z.1.element.json",
    "16": "dyall/dyall-ae2z.1.element.json",
    "17": "dyall/dyall-ae2z.1.element.json",
    "18": "dyall/dyall-ae2z.1.element.json",
    "19": "dyall/dyall-ae2z.1.element.json",
    "20": "dyall/dyall-ae2z.1.element.json",
    "21": "dyall/dyall-ae2z.1.element.json",
    "22": "dyall/dyall-ae2z.1.element.json",
    "23": "dyall/dyall-ae2z.1.element.json",
    "24": "dyall/dyall-ae2z.1.element.json",
    "25": "dyall/dyall-ae2z.1.element.json",
    "26": "dyall/dyall-ae2z.1.element.json",
    "27": "dyall/dyall-ae2z.1.element.json",
    "28": "dyall/dyall-ae2z.1.element.json",
    "29": "dyall/dyall-ae2z.1.element.json",
    "30": "dyall/dyall-ae2z.1.element.json",
    "31": "dyall/dyall-ae2z.1.element.json",
    "32": "dyall/dyall-ae2z.1.element.json",
    "33": "dyall/dyall-ae2z.1.element.json",
    "34": "dyall/dyall-ae2z.1.element.json",
    "35": "dyall/dyall-ae2z.1.element.json",
    "36": "dyall/dyall-ae2z.1.element.json",
    "37": "dyall/dyall-ae2z.1.element.json",
    "38": "dyall/dyall-ae2z.1.element.json",
    "39": "dyall/dyall-ae2z.1.element.json",
    "40": "dyall/dyall-ae2z.1.element.json",
    "41": "dyall/dyall-ae2z.1.element.json",
    "42": "dyall/dyall-ae2z.1.element.json",
    "43": "dyall/dyall-ae2z.1.element.json",
    "44": "dyall/dyall-ae2z.1.element.json",
    "45": "dyall/dyall-ae2z.1.element.json",
    "46": "dyall/dyall-ae2z.1.element.json",
    "47": "dyall/dyall-ae2z.1.element.json",
    "48": "dyall/dyall-ae2z.1.element.json",
    "49": "dyall/dyall-ae2z.1.element.json",
    "50": "dyall/dyall-ae2z.1.element.json",
    "51": "dyall/dyall-ae2z.1.element.json",
    "52": "dyall/dyall-ae2z.1.element.json",
    "53": "dyall/dyall-ae2z.1.element.json",
    "54": "dyall/dyall-ae2z.1.element.json",
    "55": "dyall/dyall-ae2z.1.element.json",
    "56": "dyall/dyall-ae2z.1.element.json",
    "57": "dyall/dyall-ae2z.1.element.json",
    "58": "dyall/dyall-ae2z.1.element.json",
    "59": "dyall/dyall-ae2z.1.element.json",
    "60": "dyall/dyall-ae2z.1.element.json",
    "61": "dyall/dyall-ae2z.1.element.json",
    "62": "dyall/dyall-ae2z.1.element.json",
    "63": "dyall/dyall-ae2z.1.element.json",
    "64": "dyall/dyall-ae2z.1.element.json",
    "65": "dyall/dyall-ae2z.1.element.json",
    "66": "dyall/dyall-ae2z.1.element.json",
    "67": "dyall/dyall-ae2z.1.element.json",
    "68": "dyall/dyall-ae2z.1.element.json",
    "69": "dyall/dyall-ae2z.1.element.json",
    "70": "dyall/dyall-ae2z.1.element.json",
    "71": "dyall/dyall-ae2z.1.element.json",
    "72": "dyall/dyall-ae2z.1.element.json",
    "73": "dyall/dyall-ae2z.1.element.json",
    "74": "dyall/dyall-ae2z.1.element.json",
    "75": "dyall/dyall-ae2z.1.element.json",
    "76": "dyall/dyall-ae2z.1.element.json",
    "77": "dyall/dyall-ae2z.1.element.json",
    "78": "dyall/dyall-ae2z.1.element.json",
    "79": "dyall/dyall-ae2z.1.element.json",
    "80": "dyall/dyall-ae2z.1.element.json",
    "81": "dyall/dyall-ae2z.1.element.json",
    "82": "dyall/dyall-ae2z.1.element.json",
    "83": "dyall/dyall-ae2z.1.element.json",
    "84": "dyall/dyall-ae2z.1.element.json",
    "85": "dyall/dyall-ae2z.1.element.json",
    "86": "dyall/dyall-ae2z.1.element.json",
    "87": "dyall/dyall-ae2z.1.element.json",
    "88": "dyall/dyall-ae2z.1.element.json",
    "89": "dyall/dyall-ae2z.1.element.json",
    "90": "dyall/dyall-ae2z.1.element.json",
    "91": "dyall/dyall-ae2z.1.element.json",
    "92": "dyall/dyall-ae2z.1.element.json",
    "93": "dyall/dyall-ae2z.1.element.json",
    "94": "dyall/dyall-ae2z.1.element.json",
    "95": "dyall/dyall-ae2z.1.element.json",
    "96": "dyall/dyall-ae2z.1.element.json",
    "97": "dyall/dyall-ae2z.1.element.json",
    "98": "dyall/dyall-ae2z.1.element.json",
    "99": "dyall/dyall-ae2z.1.element.json",
    "100": "dyall/dyall-ae2z.1.element.json",
    "101": "dyall/dyall-ae2z.1.element.json",
    "102": "dyall/dyall-ae2z.1.element.json",
    "103": "dyall/dyall-ae2z.1.element.json",
    "104": "dyall/dyall-ae2z.1.element.json",
    "105": "dyall/dyall-ae2z.1.element.json",
    "106": "dyall/dyall-ae2z.1.element.json",
    "107": "dyall/dyall-ae2z.1.element.json",
    "108": "dyall/dyall-ae2z.1.element.json",
    "109": "dyall/dyall-ae2z.1.element.json",
    "110": "dyall/dyall-ae2z.1.element.json",
    "111": "dyall/dyall-ae2z.1.element.json",
    "112": "dyall/dyall-ae2z.1.element.json",
    "113": "dyall/dyall-ae2z.1.element.json",
    "114": "dyall/dyall-ae2z.1.element.json",
    "115": "dyall/dyall-ae2z.1.element.json",
    "116": "dyall/dyall-ae2z.1.element.json",
    "117": "dyall/dyall-ae2z.1.element.json",
    "118": "dyall/dyall-ae2z.1.element.json"
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/dyall-aae3z.1.table.json
{
  "molssi_bse_schema": {
    "schema_type": "table",
    "schema_version": "0.1"
  },
  "revision_description": "Data from https://zenodo.org/records/7574629",
  "revision_date": "2024-11-17",
  "elements": {
    "1": "dyall/dyall-aae3z.1.element.json",
    "2": "dyall/dyall-aae3z.1.element.json",
    "3": "dyall/dyall-aae3z.1.element.json",
    "4": "dyall/dyall-aae3z.1.element.json",
    "5": "dyall/dyall-aae3z.1.element.json",
    "6": "dyall/dyall-aae3z.1.element.json",
    "7": "dyall/dyall-aae3z.1.element.json",
    "8": "dyall/dyall-aae3z.1.element.json",
    "9": "dyall/dyall-aae3z.1.element.json",
    "10": "dyall/dyall-aae3z.1.element.json",
    "11": "dyall/dyall-aae3z.1.element.json",
    "12": "dyall/dyall-aae3z.1.element.json",
    "13": "dyall/dyall-aae3z.1.element.json",
    "14": "dyall/dyall-aae3z.1.element.json",
    "15": "dyall/dyall-aae3z.1.element.json",
    "16": "dyall/dyall-aae3z.1.element.json",
    "17": "dyall/dyall-aae3z.1.element.json",
    "18": "dyall/dyall-aae3z.1.element.json",
    "19": "dyall/dyall-aae3z.1.element.json",
    "20": "dyall/dyall-aae3z.1.element.json",
    "21": "dyall/dyall-aae3z.1.element.json",
    "22": "dyall/dyall-aae3z.1.element.json",
    "23": "dyall/dyall-aae3z.1.element.json",
    "24": "dyall/dyall-aae3z.1.element.json",
    "25": "dyall/dyall-aae3z.1.element.json",
    "26": "dyall/dyall-aae3z.1.element.json",
    "27": "dyall/dyall-aae3z.1.element.json",
    "28": "dyall/dyall-aae3z.1.element.json",
    "29": "dyall/dyall-aae3z.1.element.json",
    "30": "dyall/dyall-aae3z.1.element.json",
    "31": "dyall/dyall-aae3z.1.element.json",
    "32": "dyall/dyall-aae3z.1.element.json",
    "33": "dyall/dyall-aae3z.1.element.json",
    "34": "dyall/dyall-aae3z.1.element.json",
    "35": "dyall/dyall-aae3z.1.element.json",
    "36": "dyall/dyall-aae3z.1.element.json",
    "37": "dyall/dyall-aae3z.1.element.json",
    "38": "dyall/dyall-aae3z.1.element.json",
    "39": "dyall/dyall-aae3z.1.element.json",
    "40": "dyall/dyall-aae3z.1.element.json",
    "41": "dyall/dyall-aae3z.1.element.json",
    "42": "dyall/dyall-aae3z.1.element.json",
    "43": "dyall/dyall-aae3z.1.element.json",
    "44": "dyall/dyall-aae3z.1.element.json",
    "45": "dyall/dyall-aae3z.1.element.json",
    "46": "dyall/dyall-aae3z.1.element.json",
    "47": "dyall/dyall-aae3z.1.element.json",
    "48": "dyall/dyall-aae3z.1.element.json",
    "49": "dyall/dyall-aae3z.1.element.json",
    "50": "dyall/dyall-aae3z.1.element.json",
    "51": "dyall/dyall-aae3z.1.element.json",
    "52": "dyall/dyall-aae3z.1.element.json",
    "53": "dyall/dyall-aae3z.1.element.json",
    "54": "dyall/dyall-aae3z.1.element.json",
    "55": "dyall/dyall-aae3z.1.element.json",
    "56": "dyall/dyall-aae3z.1.element.json",
    "72": "dyall/dyall-aae3z.1.element.json",
    "73": "dyall/dyall-aae3z.1.element.json",
    "74": "dyall/dyall-aae3z.1.element.json",
    "75": "dyall/dyall-aae3z.1.element.json",
    "76": "dyall/dyall-aae3z.1.element.json",
    "77": "dyall/dyall-aae3z.1.element.json",
    "78": "dyall/dyall-aae3z.1.element.json",
    "79": "dyall/dyall-aae3z.1.element.json",
    "80": "dyall/dyall-aae3z.1.element.json",
    "81": "dyall/dyall-aae3z.1.element.json",
    "82": "dyall/dyall-aae3z.1.element.json",
    "83": "dyall/dyall-aae3z.1.element.json",
    "84": "dyall/dyall-aae3z.1.element.json",
    "85": "dyall/dyall-aae3z.1.element.json",
    "86": "dyall/dyall-aae3z.1.element.json",
    "87": "dyall/dyall-aae3z.1.element.json",
    "88": "dyall/dyall-aae3z.1.element.json",
    "104": "dyall/dyall-aae3z.1.element.json",
    "105": "dyall/dyall-aae3z.1.element.json",
    "106": "dyall/dyall-aae3z.1.element.json",
    "107": "dyall/dyall-aae3z.1.element.json",
    "108": "dyall/dyall-aae3z.1.element.json",
    "109": "dyall/dyall-aae3z.1.element.json",
    "110": "dyall/dyall-aae3z.1.element.json",
    "111": "dyall/dyall-aae3z.1.element.json",
    "112": "dyall/dyall-aae3z.1.element.json",
    "113": "dyall/dyall-aae3z.1.element.json",
    "114": "dyall/dyall-aae3z.1.element.json",
    "115": "dyall/dyall-aae3z.1.element.json",
    "116": "dyall/dyall-aae3z.1.element.json",
    "117": "dyall/dyall-aae3z.1.element.json",
    "118": "dyall/dyall-aae3z.1.element.json"
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/jorge-DZP-ZORA.1.table.json
{
  "molssi_bse_schema": {
    "schema_type": "table",
    "schema_version": "0.1"
  },
  "revision_description": "Data from authors",
  "revision_date": "2024-12-04",
  "elements": {
    "1": "jorge/DZP-ZORA.1.element.json",
    "2": "jorge/DZP-ZORA.1.element.json",
    "3": "jorge/DZP-ZORA.1.element.json",
    "4": "jorge/DZP-ZORA.1.element.json",
    "5": "jorge/DZP-ZORA.1.element.json",
    "6": "jorge/DZP-ZORA.1.element.json",
    "7": "jorge/DZP-ZORA.1.element.json",
    "8": "jorge/DZP-ZORA.1.element.json",
    "9": "jorge/DZP-ZORA.1.element.json",
    "10": "jorge/DZP-ZORA.1.element.json",
    "11": "jorge/DZP-ZORA.1.element.json",
    "12": "jorge/DZP-ZORA.1.element.json",
    "13": "jorge/DZP-ZORA.1.element.json",
    "14": "jorge/DZP-ZORA.1.element.json",
    "15": "jorge/DZP-ZORA.1.element.json",
    "16": "jorge/DZP-ZORA.1.element.json",
    "17": "jorge/DZP-ZORA.1.element.json",
    "18": "jorge/DZP-ZORA.1.element.json",
    "19": "jorge/DZP-ZORA.1.element.json",
    "20": "jorge/DZP-ZORA.1.element.json",
    "21": "jorge/DZP-ZORA.1.element.json",
    "22": "jorge/DZP-ZORA.1.element.json",
    "23": "jorge/DZP-ZORA.1.element.json",
    "24": "jorge/DZP-ZORA.1.element.json",
    "25": "jorge/DZP-ZORA.1.element.json",
    "26": "jorge/DZP-ZORA.1.element.json",
    "27": "jorge/DZP-ZORA.1.element.json",
    "28": "jorge/DZP-ZORA.1.element.json",
    "29": "jorge/DZP-ZORA.1.element.json",
    "30": "jorge/DZP-ZORA.1.element.json",
    "31": "jorge/DZP-ZORA.1.element.json",
    "32": "jorge/DZP-ZORA.1.element.json",
    "33": "jorge/DZP-ZORA.1.element.json",
    "34": "jorge/DZP-ZORA.1.element.json",
    "35": "jorge/DZP-ZORA.1.element.json",
    "36": "jorge/DZP-ZORA.1.element.json",
    "37": "jorge/DZP-ZORA.1.element.json",
    "38": "jorge/DZP-ZORA.1.element.json",
    "39": "jorge/DZP-ZORA.1.element.json",
    "40": "jorge/DZP-ZORA.1.element.json",
    "41": "jorge/DZP-ZORA.1.element.json",
    "42": "jorge/DZP-ZORA.1.element.json",
    "43": "jorge/DZP-ZORA.1.element.json",
    "44": "jorge/DZP-ZORA.1.element.json",
    "45": "jorge/DZP-ZORA.1.element.json",
    "46": "jorge/DZP-ZORA.1.element.json",
    "47": "jorge/DZP-ZORA.1.element.json",
    "48": "jorge/DZP-ZORA.1.element.json",
    "49": "jorge/DZP-ZORA.1.element.json",
    "50": "jorge/DZP-ZORA.1.element.json",
    "51": "jorge/DZP-ZORA.1.element.json",
    "52": "jorge/DZP-ZORA.1.element.json",
    "53": "jorge/DZP-ZORA.1.element.json",
    "54": "jorge/DZP-ZORA.1.element.json",
    "55": "jorge/DZP-ZORA.1.element.json",
    "56": "jorge/DZP-ZORA.1.element.json",
    "57": "jorge/DZP-ZORA.1.element.json",
    "72": "jorge/DZP-ZORA.1.element.json",
    "73": "jorge/DZP-ZORA.1.element.json",
    "74": "jorge/DZP-ZORA.1.element.json",
    "75": "jorge/DZP-ZORA.1.element.json",
    "76": "jorge/DZP-ZORA.1.element.json",
    "77": "jorge/DZP-ZORA.1.element.json",
    "78": "jorge/DZP-ZORA.1.element.json",
    "79": "jorge/DZP-ZORA.1.element.json",
    "80": "jorge/DZP-ZORA.1.element.json",
    "81": "jorge/DZP-ZORA.1.element.json",
    "82": "jorge/DZP-ZORA.1.element.json",
    "83": "jorge/DZP-ZORA.1.element.json",
    "84": "jorge/DZP-ZORA.1.element.json",
    "85": "jorge/DZP-ZORA.1.element.json",
    "86": "jorge/DZP-ZORA.1.element.json",
    "87": "jorge/DZP-ZORA.1.element.json",
    "88": "jorge/DZP-ZORA.1.element.json",
    "89": "jorge/DZP-ZORA.1.element.json"
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/vdzp.1.table.json
{
  "molssi_bse_schema": {
    "schema_type": "table",
    "schema_version": "0.1"
  },
  "revision_description": "Data from supporting information; re-added d-type ECP on F with vanishingly small coefficient to ensure basis is correctly parsed in all programs",
  "revision_date": "2024-08-17",
  "elements": {
    "1": "grimme/vdzp.1.element.json",
    "2": "grimme/vdzp.1.element.json",
    "3": "grimme/vdzp.1.element.json",
    "4": "grimme/vdzp.1.element.json",
    "5": "grimme/vdzp.1.element.json",
    "6": "grimme/vdzp.1.element.json",
    "7": "grimme/vdzp.1.element.json",
    "8": "grimme/vdzp.1.element.json",
    "9": "grimme/vdzp.1.element.json",
    "10": "grimme/vdzp.1.element.json",
    "11": "grimme/vdzp.1.element.json",
    "12": "grimme/vdzp.1.element.json",
    "13": "grimme/vdzp.1.element.json",
    "14": "grimme/vdzp.1.element.json",
    "15": "grimme/vdzp.1.element.json",
    "16": "grimme/vdzp.1.element.json",
    "17": "grimme/vdzp.1.element.json",
    "18": "grimme/vdzp.1.element.json",
    "19": "grimme/vdzp.1.element.json",
    "20": "grimme/vdzp.1.element.json",
    "21": "grimme/vdzp.1.element.json",
    "22": "grimme/vdzp.1.element.json",
    "23": "grimme/vdzp.1.element.json",
    "24": "grimme/vdzp.1.element.json",
    "25": "grimme/vdzp.1.element.json",
    "26": "grimme/vdzp.1.element.json",
    "27": "grimme/vdzp.1.element.json",
    "28": "grimme/vdzp.1.element.json",
    "29": "grimme/vdzp.1.element.json",
    "30": "grimme/vdzp.1.element.json",
    "31": "grimme/vdzp.1.element.json",
    "32": "grimme/vdzp.1.element.json",
    "33": "grimme/vdzp.1.element.json",
    "34": "grimme/vdzp.1.element.json",
    "35": "grimme/vdzp.1.element.json",
    "36": "grimme/vdzp.1.element.json",
    "37": "grimme/vdzp.1.element.json",
    "38": "grimme/vdzp.1.element.json",
    "39": "grimme/vdzp.1.element.json",
    "40": "grimme/vdzp.1.element.json",
    "41": "grimme/vdzp.1.element.json",
    "42": "grimme/vdzp.1.element.json",
    "43": "grimme/vdzp.1.element.json",
    "44": "grimme/vdzp.1.element.json",
    "45": "grimme/vdzp.1.element.json",
    "46": "grimme/vdzp.1.element.json",
    "47": "grimme/vdzp.1.element.json",
    "48": "grimme/vdzp.1.element.json",
    "49": "grimme/vdzp.1.element.json",
    "50": "grimme/vdzp.1.element.json",
    "51": "grimme/vdzp.1.element.json",
    "52": "grimme/vdzp.1.element.json",
    "53": "grimme/vdzp.1.element.json",
    "54": "grimme/vdzp.1.element.json",
    "55": "grimme/vdzp.1.element.json",
    "56": "grimme/vdzp.1.element.json",
    "57": "grimme/vdzp.1.element.json",
    "58": "grimme/vdzp.1.element.json",
    "59": "grimme/vdzp.1.element.json",
    "60": "grimme/vdzp.1.element.json",
    "61": "grimme/vdzp.1.element.json",
    "62": "grimme/vdzp.1.element.json",
    "63": "grimme/vdzp.1.element.json",
    "64": "grimme/vdzp.1.element.json",
    "65": "grimme/vdzp.1.element.json",
    "66": "grimme/vdzp.1.element.json",
    "67": "grimme/vdzp.1.element.json",
    "68": "grimme/vdzp.1.element.json",
    "69": "grimme/vdzp.1.element.json",
    "70": "grimme/vdzp.1.element.json",
    "71": "grimme/vdzp.1.element.json",
    "72": "grimme/vdzp.1.element.json",
    "73": "grimme/vdzp.1.element.json",
    "74": "grimme/vdzp.1.element.json",
    "75": "grimme/vdzp.1.element.json",
    "76": "grimme/vdzp.1.element.json",
    "77": "grimme/vdzp.1.element.json",
    "78": "grimme/vdzp.1.element.json",
    "79": "grimme/vdzp.1.element.json",
    "80": "grimme/vdzp.1.element.json",
    "81": "grimme/vdzp.1.element.json",
    "82": "grimme/vdzp.1.element.json",
    "83": "grimme/vdzp.1.element.json",
    "84": "grimme/vdzp.1.element.json",
    "85": "grimme/vdzp.1.element.json",
    "86": "grimme/vdzp.1.element.json"
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/4zap.1.table.json
{
  "molssi_bse_schema": {
    "schema_type": "table",
    "schema_version": "0.1"
  },
  "revision_description": "Data from Supplementary Material",
  "revision_date": "2024-07-15",
  "elements": {
    "1": "ranasinghe/4zap.1.element.json",
    "6": "ranasinghe/4zap.1.element.json",
    "7": "ranasinghe/4zap.1.element.json",
    "8": "ranasinghe/4zap.1.element.json",
    "9": "ranasinghe/4zap.1.element.json"
  }
}

=== romazhukov/molopt/venv/lib/python3.8/site-packages/basis_set_exchange/data/paw-l2-contracted.1.table.json
{
  "molssi_bse_schema": {
    "schema_type": "table",
    "schema_version": "0.1"
  },
  "revision_description": "Data from supporting information",
  "revision_date": "2024-02-20",
  "elements": {
    "1": "paw/paw-l2-contracted.1.element.json",
    "3": "paw/paw-l2-contracted.1.element.json",
    "4": "paw/paw-l2-contracted.1.element.json",
    "5": "paw/paw-l2-contracted.1.element.json",
    "6": "paw/paw-l2-contracted.1.element.json",
    "7": "paw/paw-l2-contracted.1.element.json",
    "8": "paw/paw-l2-contracted.1.element.json",
    "9": "paw/paw-l2-contracted.1.element.json",
    "11": "paw/paw-l2-contracted.1.element.json",
    "12": "paw/paw-l2-contracted.1.element.json",
    "13": "paw/paw-l2-contracted.1.element.json",
    "14": "paw/paw-l2-contracted.1.element.json",
    "15": "paw/paw-l2-contracted.1.element.json",
    "16": "paw/paw-l2-contracted.1.element.json",
    "17": "paw/paw-l2-contracted.1.element.json"
  }
}
